### ISSUE TITLE
Destroying kafka triggers 100 ms sleep

### ISSUE THREAD

**Issue by Tezd** [edenhill/librdkafka#1895]
Description
===========
Destroying rdkafka adds 100 ms latency due to `rdkafka_broker.c` line of code `rd_usleep(100*1000/*100ms*/, &rk->rk_terminate);`  Those changes were made in `1c044abc59063fab56001d016b44d54374a67b2a` commit with message about memory leak. Is there any way of avoiding these 100 ms sleep or I am hitting it due to some misconfiguration?

How to reproduce
================
1. Bring up environment with docker and docker-compose as follows:
```
version: "3.6"

services:
  zookeeper:
    image: zookeeper:3.4.11

  kafka:
    image: wurstmeister/kafka:1.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 42
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
```
2.  Add `rd_rkb_dbg(rkb, GENERIC, "SLEEP", "Sleeping for 100 ms");` before https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L3562 to verify that we are hitting that condition.
3. modify examples/rdkafka_simple_producer.c as follows: 
[rdkafka_simple_producer.c](https://github.com/edenhill/librdkafka/files/2223043/rdkafka_simple_producer.txt)
4. `cd ${LIBRDKAFKA_DIR}/examples && make rdkafka_simple_producer`
5. `time ./rdkafka_simple_producer 127.0.0.1 test`
6. Verify that it sleeps for 100 ms

Checklist
=========

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `v.0.11.5`
 - [x] Apache Kafka version: `1.0.0`
 - [x] librdkafka client configuration: `debug=all`
 - [x] Operating system: `Ubuntu 16.04.1`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka 
[librdkafka.log](https://github.com/edenhill/librdkafka/files/2223083/librdkafka.txt)
 - [x] Provide broker log excerpts (they are empty for test run but will provide startup logs) 
[brokers.log](https://github.com/edenhill/librdkafka/files/2223093/brokers.txt)
 - [ ] Critical issue
