### ISSUE TITLE
rdkafka mock using C++ API end up with 'Required feature not supported by broker' (Error code: -165)

### ISSUE THREAD

**Issue by quentingodeau** [edenhill/librdkafka#2693]
Description
===========
I'm trying to create a integration test in C++ using the high level API. I end up with the following error from RdKafka: 
`Required feature not supported by broker`
Error code: `-165`

I can read in the mock code that it does not support consumer group yet. 
Does the error I'm facing is related to this limitation ?
If it's the case, how can I use the high level KafkaConsumer API that make `group.id` mandatory.

How to reproduce
================
Here below the code used:

```cpp
  // Create kafka mock cluster
  char             errstr[256];
  rd_kafka_conf_t *conf = rd_kafka_conf_new();
  rd_kafka_t *     rk   = rd_kafka_new(RD_KAFKA_PRODUCER, conf, errstr, sizeof(errstr));
  ASSERT_TRUE(nullptr != rk) << "Failed to create mock cluster rd_kafka_t: " << errstr;

  rd_kafka_mock_cluster_t *mcluster = rd_kafka_mock_cluster_new(rk, 3 /* broker_cnt */);
  ASSERT_TRUE(nullptr != mcluster) << "Failed to acquire mock cluster";

  const char *bootstraps = rd_kafka_mock_cluster_bootstraps(mcluster);

  // Set env KAFKA_BROKER variable with the addresses of the mock cluster
  setenv("KAFKA_BROKER", bootstraps, 1);

  // For clarity I do not detail the creation code
  // Creation of RdKafka::Producer
  // Creation of RdKafka::KafkaConsumer


  // Destroy mock cluster
  rd_kafka_mock_cluster_destroy(mcluster);
  rd_kafka_destroy(rk);
```

Configuration:
```yaml
kafka:
  configuration:
    metadata.broker.list: ${KAFKA_BROKER:""}
    client.id: MOCK
    # Think this is not supported and failed on consume...
    group.id: test-integration
    #enable.auto.commit: false
    #enable.partition.assignment: false
    # broker.version.fallback: '0.9.0'
    api.version.request: true
    max.poll.interval.ms: 10000
    # test.mock.num.brokers: 3
  topics:
    my-topic-name:
      name: real-name-of-the-topic
```

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

 - [x] librdkafka version (release number or git tag): `1.3.0>`
 - [x] Apache Kafka version: `N/A (mock)`
 - [x] librdkafka client configuration: `provide in section 'How to reproduce'`
 - [x] Operating system: `Centos 7 (x64) but sample code is compiled in 32 bits`
 - [ ] Provide logs (with `debug=..` as necessary) from librdkafka
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
