### ISSUE TITLE
Improve configure --libdir (etc) help texts

### ISSUE THREAD

**Issue by theidexisted** [edenhill/librdkafka#3367]
Read the FAQ first: https://github.com/edenhill/librdkafka/wiki/FAQ

Description
===========
To link rdkafka with prebuilt openssl and sasl, we use `libdir` to specify the 3rparty library path.  To install the library with a specific path(Which is useful in docker) we will configure it with `prefix` option.

But then the library(librdkafka.so) will be copied into `libdir`, which is expected to into `prefix`, this is a bug.

How to reproduce
================

```
./configure --prefx=/tmp/rd_install --libdir=$3RDPARTY_LIB_DIR
make -j$(nproc)
make install
```

Then check `/tmp/rd_install`  and `$3RDPARTY_LIB_DIR` to find that the libraries in `$3RDPARTY_LIB_DIR`

**IMPORTANT**: Always try to reproduce the issue on the latest released version (see https://github.com/edenhill/librdkafka/releases), if it can't be reproduced on the latest version the issue has been fixed.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed.

Please provide the following information:

 - [x] librdkafka version (release number or git tag): `<1.6.1>`
 - [x] Apache Kafka version: `<NULL>`
 - [x] librdkafka client configuration: `<NULL>`
 - [x] Operating system: `<Rhel 7>`
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka:NULL
 - [x] Provide broker log excerpts:NULL
 - [ ] Critical issue

**Comment by edenhill** [comment]
--prefix is the default prefix for libdir, et.al, but you are overriding it with --libdir, so the outcome is expected.

**Comment by theidexisted** [comment]
Does `libdir` aim to be the input path of other dependent libraries (openssl and sasl)?

**Comment by edenhill** [comment]
libdir is the installation directory for the built libraries (librdkafka.so.1 and librdkafka++.so.1)

Use LIBS to add dependency library search paths, e.g:
`LIBS=$3RD_PARTY_LIB_DIR ./configure --prefix=/where-to-install-librdkafka`

**Comment by theidexisted** [comment]
Thank you so much!

**Comment by edenhill** [comment]
see https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Installation-Directory-Variables.html

**Comment by theidexisted** [comment]
So for depend on library head path, we need to use `CPPFLAGS="-I $HEAD_PATH`, is it right?

**Comment by edenhill** [comment]
Yep, like so:
`LIBS="/other/path/libs" CPPFLAGS="-I/other/path/includes" ./configure ..`

or use pkg-config (set PKG_CONFIG_PATH=/where/third/party/.pc-files-reside) if .pc files are available.

**Comment by theidexisted** [comment]
Thanks again, your response is so rapid!

**Comment by theidexisted** [comment]
I also suggest refine this document:

```
Standard options:
   --prefix=PATH                        Install arch-independent files in PATH [/usr/local]                                                                                                                           --exec-prefix=PATH                   Install arch-dependent files in PATH [$prefix]
   --bindir=PATH                        User executables [$exec_prefix/bin]
   --sbindir=PATH                       System admin executables [$exec_prefix/sbin]
   --libexecdir=PATH                    Program executables [$exec_prefix/libexec]
   --datadir=PATH                       Read-only arch-independent data [$prefix/share]
   --sysconfdir=PATH                    Configuration data [$prefix/etc]
   --sharedstatedir=PATH                Modifiable arch-independent data [$prefix/com]
   --localstatedir=PATH                 Modifiable local state data [$prefix/var]
   --runstatedir=PATH                   Modifiable per-process data [$prefix/var/run]
   --libdir=PATH                        Libraries [$exec_prefix/lib]
   --includedir=PATH                    C/C++ header files [$prefix/include]
   --infodir=PATH                       Info documentation [$prefix/info]
   --mandir=PATH                        Manual pages [$prefix/man]
```

To add installation hints, nowadays we don't have rich knowledge of the build tools as you experts, the detailed document will be very helpful.

**Comment by edenhill** [comment]
Thanks, will do :+1:

**Comment by theidexisted** [comment]
I have tried to pass `LIBS` but get configure fails:

```

###########################################################
###                  Configure failed                   ###
###########################################################
### Accumulated failures:                               ###
###########################################################
 libsasl2 (WITH_SASL_CYRUS) 
    module: self
    action: fail
    reason:
compile check failed:
CC: CC
flags: -lsasl2
gcc  -I/var/dependency_include -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align -Wall -Werror _mkltmpat1zlz.c -o _mkltmpat1zlz.c.o   -lsasl2:
```

Seems this [function ](https://github.com/edenhill/librdkafka/blob/master/mklove/modules/configure.base#L1310)haven't deal with the `LIBS` environemnt variable, is it an issue?
